/* eslint-disable */
// Generated by Wrangler by running `wrangler types`
// Runtime types generated with workerd
declare namespace Cloudflare {
  interface GlobalProps {}
  interface Env {}
}
interface Env extends Cloudflare.Env {}
